image: 
  name: immcantation/test:4.2.0

pipelines:
  default:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_dep.R
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings
