site_name: scoper
repo_url: https://bitbucket.org/kleinstein/scoper
edit_uri: src/master/docs/
theme: readthedocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: 'docs'
nav:
  - 'Immcantation Portal': 'https://immcantation.readthedocs.io'
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/scoper.md
    - 'Release Notes': news.md
  - 'Vignettes':
    - 'Clonal Partitioning': vignettes/Scoper-Vignette.md
  - 'Help Topics':
    - topics/identicalClones.md
    - topics/hierarchicalClones.md
    - topics/spectralClones.md
    - topics/plotCloneSummary.md
    - topics/ScoperClones-class.md
    - topics/ExampleDb.md
