site_name: scope
theme: readthedocs
repo_url: https://bitbucket.org/kleinstein/scope
docs_dir: docs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - pymdownx.arithmatex
  - toc:
      permalink: True
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Package Overview': topics/scope.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Clonal partitioning': vignettes/scope-Vignette.md
  - 'Help Topics':
    - topics/defineClonesScope.md
    - topics/clonesAnalysis.md
    - topics/ClonesAnalysisResult-class.md
    - topics/ExampleDb.md
