site_name: scoper
site_favicon: img/immcantation.ico
repo_url: https://bitbucket.org/kleinstein/scoper
theme: readthedocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: 'docs'
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/scoper.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Clonal partitioning': vignettes/Scoper-Vignette.md
  - 'Help Topics':
    - topics/defineClonesScoper.md
    - topics/ExampleDb.md
