name: alakazam groupGenes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unittest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: immcantation/test:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sed -i '/test/ d' .Rbuildignore
          Rscript tests/setup/install_dep.R
          
          Rscript -e "devtools::install_github('immcantation/alakazam@groupGenes')"
      - name: Document
        run: |
          install.packages('lifecycle')
          devtools::document()
        shell: Rscript {0}
      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
          options(crayon.enabled=TRUE)
          rcmdcheck::rcmdcheck(args = c("--as-cran", "--run-donttest", "--timings"), error_on="warning", check_dir="check")
        shell: Rscript {0}